type ButtonConfig = {
  size: "large" | "medium" | "small" | "extra-small";
  color: "primary" | "secondary" | "error";
  variant: "solid" | "light" | "no-background" | "outline" | "link";
  isDisabled: boolean;
  isLoading: boolean;
};

export const solidButtonConfigs: ButtonConfig[] = [
  {
    size: "large",
    color: "primary",
    variant: "solid",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "medium",
    color: "primary",
    variant: "solid",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "small",
    color: "primary",
    variant: "solid",
    isDisabled: true,
    isLoading: false,
  },
  {
    size: "extra-small",
    color: "primary",
    variant: "solid",
    isDisabled: false,
    isLoading: true,
  },
  {
    size: "large",
    color: "secondary",
    variant: "solid",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "medium",
    color: "secondary",
    variant: "solid",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "small",
    color: "secondary",
    variant: "solid",
    isDisabled: true,
    isLoading: false,
  },
  {
    size: "extra-small",
    color: "secondary",
    variant: "solid",
    isDisabled: false,
    isLoading: true,
  },
  {
    size: "large",
    color: "error",
    variant: "solid",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "medium",
    color: "error",
    variant: "solid",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "small",
    color: "error",
    variant: "solid",
    isDisabled: true,
    isLoading: false,
  },
  {
    size: "extra-small",
    color: "error",
    variant: "solid",
    isDisabled: false,
    isLoading: true,
  },
];

export const lightButtonConfigs: ButtonConfig[] = [
  {
    size: "large",
    color: "primary",
    variant: "light",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "medium",
    color: "primary",
    variant: "light",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "small",
    color: "primary",
    variant: "light",
    isDisabled: true,
    isLoading: false,
  },
  {
    size: "extra-small",
    color: "primary",
    variant: "light",
    isDisabled: false,
    isLoading: true,
  },
  {
    size: "large",
    color: "secondary",
    variant: "light",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "medium",
    color: "secondary",
    variant: "light",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "small",
    color: "secondary",
    variant: "light",
    isDisabled: true,
    isLoading: false,
  },
  {
    size: "extra-small",
    color: "secondary",
    variant: "light",
    isDisabled: false,
    isLoading: true,
  },
  {
    size: "large",
    color: "error",
    variant: "light",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "medium",
    color: "error",
    variant: "light",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "small",
    color: "error",
    variant: "light",
    isDisabled: true,
    isLoading: false,
  },
  {
    size: "extra-small",
    color: "error",
    variant: "light",
    isDisabled: false,
    isLoading: true,
  },
];

export const noBGButtonConfigs: ButtonConfig[] = [
  {
    size: "large",
    color: "primary",
    variant: "no-background",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "medium",
    color: "primary",
    variant: "no-background",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "small",
    color: "primary",
    variant: "no-background",
    isDisabled: true,
    isLoading: false,
  },
  {
    size: "extra-small",
    color: "primary",
    variant: "no-background",
    isDisabled: false,
    isLoading: true,
  },
  {
    size: "large",
    color: "secondary",
    variant: "no-background",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "medium",
    color: "secondary",
    variant: "no-background",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "small",
    color: "secondary",
    variant: "no-background",
    isDisabled: true,
    isLoading: false,
  },
  {
    size: "extra-small",
    color: "secondary",
    variant: "no-background",
    isDisabled: false,
    isLoading: true,
  },
  {
    size: "large",
    color: "error",
    variant: "no-background",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "medium",
    color: "error",
    variant: "no-background",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "small",
    color: "error",
    variant: "no-background",
    isDisabled: true,
    isLoading: false,
  },
  {
    size: "extra-small",
    color: "error",
    variant: "no-background",
    isDisabled: false,
    isLoading: true,
  },
];

export const outlineButtonConfigs: ButtonConfig[] = [
  {
    size: "large",
    color: "primary",
    variant: "outline",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "medium",
    color: "primary",
    variant: "outline",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "small",
    color: "primary",
    variant: "outline",
    isDisabled: true,
    isLoading: false,
  },
  {
    size: "extra-small",
    color: "primary",
    variant: "outline",
    isDisabled: false,
    isLoading: true,
  },
  {
    size: "large",
    color: "secondary",
    variant: "outline",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "medium",
    color: "secondary",
    variant: "outline",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "small",
    color: "secondary",
    variant: "outline",
    isDisabled: true,
    isLoading: false,
  },
  {
    size: "extra-small",
    color: "secondary",
    variant: "outline",
    isDisabled: false,
    isLoading: true,
  },
  {
    size: "large",
    color: "error",
    variant: "outline",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "medium",
    color: "error",
    variant: "outline",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "small",
    color: "error",
    variant: "outline",
    isDisabled: true,
    isLoading: false,
  },
  {
    size: "extra-small",
    color: "error",
    variant: "outline",
    isDisabled: false,
    isLoading: true,
  },
];

export const linkButtonConfigs: ButtonConfig[] = [
  {
    size: "large",
    color: "primary",
    variant: "link",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "medium",
    color: "primary",
    variant: "link",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "small",
    color: "primary",
    variant: "link",
    isDisabled: true,
    isLoading: false,
  },
  {
    size: "extra-small",
    color: "primary",
    variant: "link",
    isDisabled: false,
    isLoading: true,
  },
  {
    size: "large",
    color: "secondary",
    variant: "link",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "medium",
    color: "secondary",
    variant: "link",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "small",
    color: "secondary",
    variant: "link",
    isDisabled: true,
    isLoading: false,
  },
  {
    size: "extra-small",
    color: "secondary",
    variant: "link",
    isDisabled: false,
    isLoading: true,
  },
  {
    size: "large",
    color: "error",
    variant: "link",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "medium",
    color: "error",
    variant: "link",
    isDisabled: false,
    isLoading: false,
  },
  {
    size: "small",
    color: "error",
    variant: "link",
    isDisabled: true,
    isLoading: false,
  },
  {
    size: "extra-small",
    color: "error",
    variant: "link",
    isDisabled: false,
    isLoading: true,
  },
];
