const dummyTableData = [
  {
    code: 656,
    beneficiary_name: "CV CIPTA ABADI REZEKI",
    phone_number: null,
    email: null,
    payment_currency: "IDR",
    bank_name: null,
    bank_address: null,
    account_number: null,
    tax_percentage: 30,
    npwp: null,
    auto_payout: null,
    notes: null,
    bank_account_holder: null,
    beneficiary_type: "Company",
    address: null,
    rt: null,
    rw: null,
    province: null,
    city: null,
    district: null,
    sub_district: null,
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 694,
    beneficiary_name: "MOHAMMAD YORRIZ ARBAA",
    phone_number: "085810314030",
    email: "yorrizarbaa@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: null,
    account_number: "6380176902",
    tax_percentage: 15,
    npwp: "82.144.019.5-045.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "MOHAMMAD YORRIZ ARBA'A",
    beneficiary_type: "Personal",
    address: "Gg Masjid II No.30",
    rt: "012",
    rw: "003",
    province: "DKI Jakarta",
    city: "Jakarta Utara",
    district: "Koja",
    sub_district: "Rawa Badak Selatan",
    postal_code: "14230",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 638,
    beneficiary_name: "PT BENGAWAN STUDIO INDONESIA",
    phone_number: null,
    email: null,
    payment_currency: "IDR",
    bank_name: null,
    bank_address: null,
    account_number: null,
    tax_percentage: 30,
    npwp: null,
    auto_payout: null,
    notes: null,
    bank_account_holder: null,
    beneficiary_type: "Company",
    address: null,
    rt: null,
    rw: null,
    province: null,
    city: null,
    district: null,
    sub_district: null,
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 650,
    beneficiary_name: "RAINDRA SAADYA RAMADHAN PRIYANTO",
    phone_number: "087785196887",
    email: "raindrapriyanto@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: "BINTARO",
    account_number: "6801277354",
    tax_percentage: 15,
    npwp: "70.293.822.6-411.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "DAENG SAROJINNI NAIDU",
    beneficiary_type: "Personal",
    address: "Vila Cendana Blok C23 Jl.Wr Supratman Kampung Utan",
    rt: "006",
    rw: "008",
    province: "Banten",
    city: "Tangerang Selatan",
    district: "Ciputat Timur",
    sub_district: "Cempaka Putih",
    postal_code: "15412",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 670,
    beneficiary_name: "PT SUPER BLAST INDONESIA",
    phone_number: null,
    email: null,
    payment_currency: "IDR",
    bank_name: null,
    bank_address: null,
    account_number: null,
    tax_percentage: 30,
    npwp: null,
    auto_payout: null,
    notes: null,
    bank_account_holder: null,
    beneficiary_type: "Company",
    address: null,
    rt: null,
    rw: null,
    province: null,
    city: null,
    district: null,
    sub_district: null,
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 692,
    beneficiary_name: "NICHOLAS YOEL SUPRIADI",
    phone_number: "08112270110",
    email: "nichyoel@gmail.com",
    payment_currency: "IDR",
    bank_name: "MANDIRI",
    bank_address: "TAMAN KOPO INDAH",
    account_number: "1300016834833",
    tax_percentage: 15,
    npwp: "07.019.314.9-424.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "DEDY SUPRIADI",
    beneficiary_type: "Personal",
    address: "Taman Kopo Indah Ii Ruko 2A No.3",
    rt: "002",
    rw: "014",
    province: "Jawa Barat",
    city: "Bandung",
    district: "Marga Asih",
    sub_district: "Rahayu",
    postal_code: "40218",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 616,
    beneficiary_name: "THERESIA MARGARETHA",
    phone_number: "087821127502",
    email: "theiya76@gmail.com, lia.tigaduasatu@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: null,
    account_number: "7774344455",
    tax_percentage: 15,
    npwp: "96.202.417.0-423.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "PT TIGADUASATU RUANG TERPADU",
    beneficiary_type: "Personal",
    address: "Jl Manunggal 1 No.19",
    rt: "011",
    rw: "006",
    province: "DKI Jakarta",
    city: "Jakarta Timur",
    district: "Makasar",
    sub_district: "Cipinang Melayu",
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 626,
    beneficiary_name: "BRIGITA SRIULINA BERU MELIALA",
    phone_number: "081806366555",
    email: "cecil.idgitafmusik@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: null,
    account_number: "4214490490",
    tax_percentage: 15,
    npwp: "62.440.294.7-013.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "PALUNG KREASI HATI PT",
    beneficiary_type: "Personal",
    address: "Bukit Cengkeh II Blok D14 No.1",
    rt: "011",
    rw: "016",
    province: "Jawa Barat",
    city: "Depok",
    district: "Cimanggis",
    sub_district: "Tugu",
    postal_code: "16451",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 623,
    beneficiary_name: "PT MUSIKA NADA SUARA",
    phone_number: null,
    email: null,
    payment_currency: "IDR",
    bank_name: null,
    bank_address: null,
    account_number: null,
    tax_percentage: 30,
    npwp: null,
    auto_payout: null,
    notes: null,
    bank_account_holder: null,
    beneficiary_type: "Company",
    address: null,
    rt: null,
    rw: null,
    province: null,
    city: null,
    district: null,
    sub_district: null,
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 641,
    beneficiary_name: "PT DUA ANAK DEO",
    phone_number: null,
    email: "finance.duaanakdeo@gmail.com",
    payment_currency: "IDR",
    bank_name: null,
    bank_address: null,
    account_number: null,
    tax_percentage: 30,
    npwp: null,
    auto_payout: null,
    notes: null,
    bank_account_holder: null,
    beneficiary_type: "Company",
    address: null,
    rt: null,
    rw: null,
    province: null,
    city: null,
    district: null,
    sub_district: null,
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 829,
    beneficiary_name: "RICKY RAMADHAN SETIYAWAN",
    phone_number: "081216384261",
    email: "welliamrick@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: "PONDOK INDAH",
    account_number: "2378888943",
    tax_percentage: 15,
    npwp: "92.562.830.7-014.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "PT SKAK KREATIF INDONESIA",
    beneficiary_type: "Personal",
    address: "Bantaran 3D No.6",
    rt: "001",
    rw: "004",
    province: "Jawa Timur",
    city: "Malang",
    district: "Lowokwaru",
    sub_district: "Tulusrejo",
    postal_code: "65141",
    c_address: "Kantor Skak Studios / Mpr III Dalam No.64",
    c_rt: "005",
    c_rw: "013",
    c_province: "DKI Jakarta",
    c_city: "Jakarta Selatan",
    c_district: "Cilandak",
    c_sub_district: "Cilandak Barat",
    c_postal_code: "12430",
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 657,
    beneficiary_name: "OKTARIADI ANIS",
    phone_number: "072797745",
    email: "anisadhaniaprianty@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: "TAMAN SOLO CEMPAKA PUTIH",
    account_number: "5680183319",
    tax_percentage: 15,
    npwp: "07.549.243.9-003.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "FARIDA ZULFIKAR",
    beneficiary_type: "Personal",
    address: "Pondasi 59A",
    rt: "012",
    rw: "002",
    province: "DKI Jakarta",
    city: "Jakarta Timur",
    district: "Pulo Gadung",
    sub_district: "Kayu Putih",
    postal_code: null,
    c_address: "Kerinci 1 No.8A",
    c_rt: null,
    c_rw: null,
    c_province: "DKI Jakarta",
    c_city: "Jakarta Selatan",
    c_district: "Kebayoran Baru",
    c_sub_district: "Gunung",
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 819,
    beneficiary_name: "ARIF SATRIA",
    phone_number: "08111803940",
    email: "arifsatria@apps.ipb.ac.id",
    payment_currency: "IDR",
    bank_name: "BNI",
    bank_address: "DRAMAGA BOGOR",
    account_number: "9880053302150102",
    tax_percentage: 15,
    npwp: "09.233.767.4-404.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "IPB TV",
    beneficiary_type: "Personal",
    address: "Jl. Bunga Canna No 3 Cluster Sierra Madre Sentul Bogor",
    rt: "004",
    rw: "006",
    province: "Jawa Barat",
    city: "Bogor",
    district: "Babakan Madang",
    sub_district: "Citaringgul",
    postal_code: "16810",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 674,
    beneficiary_name: "EFLINE TIARMA S",
    phone_number: "087872729370",
    email: "contact.jebung@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: null,
    account_number: "6241313309",
    tax_percentage: 15,
    npwp: "42.498.521.6-004.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "JESSICA SABAR BUNGAULI SILABAN",
    beneficiary_type: "Personal",
    address: "Jl Utama V No 17",
    rt: "005",
    rw: "005",
    province: "DKI Jakarta",
    city: "Jakarta Timur",
    district: "Duren Sawit",
    sub_district: "Pondok Bambu",
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 822,
    beneficiary_name: "KOESNOMO KOESWOYO",
    phone_number: "085803313581",
    email: "rezawicaksono18hwm@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: null,
    account_number: "3440275361",
    tax_percentage: 15,
    npwp: "61.854.717.8-524.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "REZA WICAKSONO",
    beneficiary_type: "Personal",
    address: "Jl. Soekarno Hatta",
    rt: "005",
    rw: "021",
    province: "Jawa Tengah",
    city: "Magelang",
    district: "Magelang Tengah",
    sub_district: "Rejowinangun Utara",
    postal_code: "56127",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 400,
    beneficiary_name: "HUSEIN AS",
    phone_number: null,
    email: null,
    payment_currency: "IDR",
    bank_name: null,
    bank_address: null,
    account_number: null,
    tax_percentage: 30,
    npwp: "#REF!",
    auto_payout: null,
    notes: null,
    bank_account_holder: null,
    beneficiary_type: "Personal",
    address: null,
    rt: null,
    rw: null,
    province: null,
    city: null,
    district: null,
    sub_district: null,
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 611,
    beneficiary_name: "MATROJI MATROJI",
    phone_number: "083877502559",
    email: "ajicetibahadursyah09@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: null,
    account_number: "7150891331",
    tax_percentage: 15,
    npwp: "44.487.895.3-412.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "MATROJI",
    beneficiary_type: "Personal",
    address: "Jl H Muhidin No.60",
    rt: "001",
    rw: "002",
    province: "Jawa Barat",
    city: "Depok",
    district: "Cipayung",
    sub_district: "Cipayung Jaya",
    postal_code: "16441",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 610,
    beneficiary_name: "HERMANTO HERMANTO",
    phone_number: "0895333236965",
    email: "hermantoimma@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: null,
    account_number: "7651009115",
    tax_percentage: 15,
    npwp: "74.606.347.8-412.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "HERMANTO",
    beneficiary_type: "Personal",
    address: "Jl H Muhidin No.14",
    rt: "002",
    rw: "002",
    province: "Jawa Barat",
    city: "Depok",
    district: "Cipayung",
    sub_district: "Cipayung Jaya",
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 619,
    beneficiary_name: "IRENE MAYLONE",
    phone_number: "08119693939",
    email: "mayloneirene@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: "PASAR LAMA",
    account_number: "1084446605",
    tax_percentage: 15,
    npwp: "34.696.111.3-416.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "IRENE MAYLONE",
    beneficiary_type: "Personal",
    address: "Jl Tegal Sari IV No 45",
    rt: "004",
    rw: "011",
    province: "Banten",
    city: "Tangerang",
    district: "Tangerang",
    sub_district: "Sukasari",
    postal_code: "15118",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 468,
    beneficiary_name: "AZIZI RESNA",
    phone_number: "082213996232",
    email: "gozil.lewe.lewe@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: null,
    account_number: "5420547856",
    tax_percentage: 15,
    npwp: "44.444.165.3.419.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "EPAH MARTINI",
    beneficiary_type: "Personal",
    address: "Jl Kh Syam'Un",
    rt: "005",
    rw: "004",
    province: "Banten",
    city: "Lebak",
    district: "Rangkasbitung",
    sub_district: "Muara Ciujung Barat",
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 471,
    beneficiary_name: "MUHAMAD RAINER BANGSAWAN",
    phone_number: null,
    email: null,
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: null,
    account_number: "7773839168",
    tax_percentage: 15,
    npwp: "92.036.244.9-421.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "M RAINER BANGSAWAN",
    beneficiary_type: "Personal",
    address: "Setra Duta Blok B No.B4.4",
    rt: "003",
    rw: "001",
    province: "Jawa Barat",
    city: "Bandung Barat",
    district: "Parongpong",
    sub_district: "Ciwaruga",
    postal_code: null,
    c_address: "Jl Cukangkawung No.24",
    c_rt: null,
    c_rw: null,
    c_province: "Jawa Barat",
    c_city: "Bandung",
    c_district: "Cibeunying Kaler",
    c_sub_district: "Cigadung",
    c_postal_code: "40191",
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 475,
    beneficiary_name: "ERWIN SUDARWIN GS",
    phone_number: "02175910053",
    email: "luftiandriani@yahoo.com",
    payment_currency: "IDR",
    bank_name: "MANDIRI",
    bank_address: "PIM 1",
    account_number: "1010004441026",
    tax_percentage: 15,
    npwp: "08.088.889.4-013.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "IR ERWIN SUDARWIN G.S",
    beneficiary_type: "Personal",
    address: "Jl Alam Elok III Uc 21/9",
    rt: "001",
    rw: "016",
    province: "DKI Jakarta",
    city: "Jakarta Selatan",
    district: "Kebayoran Lama",
    sub_district: "Pondok Pinang",
    postal_code: null,
    c_address: "Jl Pangeran Antasari No.80",
    c_rt: "012",
    c_rw: "013",
    c_province: "DKI Jakarta",
    c_city: "Jakarta Selatan",
    c_district: "Cilandak",
    c_sub_district: "Cilandak Barat",
    c_postal_code: "12430",
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 480,
    beneficiary_name: "REZA RAHADIAN MATULESSY",
    phone_number: "08111088087",
    email: "contact.rezarahadian@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: null,
    account_number: "7330355934",
    tax_percentage: 15,
    npwp: "25.355.240.0.412.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "ISMAIL IBRAHIM",
    beneficiary_type: "Personal",
    address: "Jl Paso No.34 Casa At Paso Kav.02",
    rt: "004",
    rw: "006",
    province: "DKI Jakarta",
    city: "Jakarta Selatan",
    district: "Jagakarsa",
    sub_district: "Jagakarsa",
    postal_code: null,
    c_address: "Jagakarsa Residence, Jl Sutera 2 C1/9",
    c_rt: null,
    c_rw: null,
    c_province: "DKI Jakarta",
    c_city: "Jakarta Selatan",
    c_district: "Jagakarsa",
    c_sub_district: "Jagakarsa",
    c_postal_code: "12620",
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 484,
    beneficiary_name: "WILBERT J DEIL",
    phone_number: "085814369031",
    email: "wilbertdeil@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: null,
    account_number: "4730045684",
    tax_percentage: 15,
    npwp: "53.297.861.6-453.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "WILBERT J. DEIL",
    beneficiary_type: "Personal",
    address: "Jl. Nangka Raya Blok G1/10 Pamulang Estate",
    rt: "005",
    rw: "013",
    province: "Banten",
    city: "Tangerang Selatan",
    district: "Pamulang",
    sub_district: "Pamulang Timur",
    postal_code: "15417",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 496,
    beneficiary_name: "ALASEN BARUS",
    phone_number: null,
    email: null,
    payment_currency: "IDR",
    bank_name: null,
    bank_address: null,
    account_number: null,
    tax_percentage: 30,
    npwp: null,
    auto_payout: null,
    notes: null,
    bank_account_holder: null,
    beneficiary_type: "Personal",
    address: null,
    rt: null,
    rw: null,
    province: null,
    city: null,
    district: null,
    sub_district: null,
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 500,
    beneficiary_name: "DANIEL MARCELINO SURYO",
    phone_number: "087773838652",
    email: "dumpycheeksmusic@gmail.com",
    payment_currency: "IDR",
    bank_name: null,
    bank_address: null,
    account_number: "0948 562491",
    tax_percentage: 30,
    npwp: null,
    auto_payout: null,
    notes: null,
    bank_account_holder: null,
    beneficiary_type: "Personal",
    address: "Jl Pemda 2 No.48",
    rt: "009",
    rw: "001",
    province: "DKI Jakarta",
    city: "Jakarta Timur",
    district: "Pulo Gadung",
    sub_district: "Rawamangun",
    postal_code: "13220",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 504,
    beneficiary_name: "MUHAMAD SAMSUDIN DAJAT HARDJAKUSUMAH",
    phone_number: "08111501395",
    email: "samsudinbimbo@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: "BANDUNG",
    account_number: "2370121250",
    tax_percentage: 15,
    npwp: "06.122.498.6-423.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "DAUD MUHAMAD SAMSUDIN",
    beneficiary_type: "Personal",
    address: "Jl Parasitologi No.15",
    rt: "002",
    rw: "007",
    province: "Jawa Barat",
    city: "Bandung",
    district: "Cibeunying Kaler",
    sub_district: "Cigadung",
    postal_code: "40191",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 512,
    beneficiary_name: "ANDRI PRIYANTO",
    phone_number: "08122735868",
    email: "priyantaandry@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: null,
    account_number: "1692017034",
    tax_percentage: 15,
    npwp: "98.149.178.0-541.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "ROSALIA MANDASIA W",
    beneficiary_type: "Personal",
    address: "Suryodiningratan Mj 2/731",
    rt: "037",
    rw: "011",
    province: "DI Yogyakarta",
    city: "Yogyakarta",
    district: "Mantrijeron",
    sub_district: "Suryodiningratan",
    postal_code: "55141",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 517,
    beneficiary_name: "PT SHELINO TRI JAYA",
    phone_number: null,
    email: null,
    payment_currency: "IDR",
    bank_name: null,
    bank_address: null,
    account_number: null,
    tax_percentage: 30,
    npwp: null,
    auto_payout: null,
    notes: null,
    bank_account_holder: null,
    beneficiary_type: "Company",
    address: null,
    rt: null,
    rw: null,
    province: null,
    city: null,
    district: null,
    sub_district: null,
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 524,
    beneficiary_name: "HAKRIE RIO AFRIANDI",
    phone_number: "02122455068",
    email: "finance.duaanakdeo@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: "RAWAMANGUN",
    account_number: "0947519909",
    tax_percentage: 15,
    npwp: "80.594.058.2-003.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "PT DUA ANAK DEO",
    beneficiary_type: "Personal",
    address: "Ujung Menteng/Cakung",
    rt: "014",
    rw: "007",
    province: "DKI Jakarta",
    city: "Jakarta Timur",
    district: "Pulo Gadung",
    sub_district: "Jati",
    postal_code: "13220",
    c_address: "Kirana Boutique Office, Jl Kirana Avenue Blok D3 No.7",
    c_rt: null,
    c_rw: null,
    c_province: "DKI Jakarta",
    c_city: "Jakarta Utara",
    c_district: "Kelapa Gading",
    c_sub_district: "Kelapa Gading Tmr",
    c_postal_code: "14240",
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 535,
    beneficiary_name: "RADEN RIANA MAYASARI",
    phone_number: "087822336604",
    email: "rianamayasari16@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: "CIMAHI",
    account_number: "1392384621",
    tax_percentage: 15,
    npwp: "34.560.330.2-422.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "R RIANA MAYASARI",
    beneficiary_type: "Personal",
    address: "Jl Pasundan No.68/18B",
    rt: "003",
    rw: "004",
    province: "Jawa Barat",
    city: "Bandung",
    district: "Regol",
    sub_district: "Balonggede",
    postal_code: "40251",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 549,
    beneficiary_name: "VAIS RANDI ACHMAD PRADITYA ARIESTA NAJAYA",
    phone_number: "082114560215",
    email: null,
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: null,
    account_number: "0790455177",
    tax_percentage: 30,
    npwp: null,
    auto_payout: null,
    notes: null,
    bank_account_holder: "VAIS RANDI ACHMAD PRADITYA AN",
    beneficiary_type: "Personal",
    address: "Jogobayan",
    rt: "001",
    rw: "006",
    province: "Jawa Tengah",
    city: "Surakarta",
    district: "Banjarsari",
    sub_district: "Setabelan",
    postal_code: null,
    c_address: "Gg Melasti No.154",
    c_rt: null,
    c_rw: null,
    c_province: "Bali",
    c_city: "Denpasar",
    c_district: "Denpasar Timur",
    c_sub_district: "Kesiman Kertalangu",
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 550,
    beneficiary_name: "FENGKY FISCHER",
    phone_number: "081224373310",
    email: "vekinfriends@gmail.com",
    payment_currency: "IDR",
    bank_name: "MANDIRI",
    bank_address: "KOTA PALU",
    account_number: "9000025162620",
    tax_percentage: 15,
    npwp: "81.253.579.7-831.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "VENGKI FISCHER",
    beneficiary_type: "Personal",
    address: "Jl Beringin No.13",
    rt: "002",
    rw: "001",
    province: "Sulawesi Tengah",
    city: "Palu",
    district: "Tatanga",
    sub_district: "Boyaoge",
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 557,
    beneficiary_name: "PT KOBRA DIMENSI MULTIMEDIA",
    phone_number: null,
    email: null,
    payment_currency: "IDR",
    bank_name: null,
    bank_address: null,
    account_number: null,
    tax_percentage: 30,
    npwp: null,
    auto_payout: null,
    notes: null,
    bank_account_holder: null,
    beneficiary_type: "Company",
    address: null,
    rt: null,
    rw: null,
    province: null,
    city: null,
    district: null,
    sub_district: null,
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 452,
    beneficiary_name: "MOCH ZULHAMDANI",
    phone_number: "082139691784",
    email: "danskiheyho@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: "MATRAMAN",
    account_number: "3423533788",
    tax_percentage: 15,
    npwp: "84.120.171.8-448.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "ESTU MUKTI MANDIRI PT",
    beneficiary_type: "Personal",
    address: "Jl H Midi No.80",
    rt: "007",
    rw: "002",
    province: "Jawa Barat",
    city: "Depok",
    district: "Limo",
    sub_district: "Limo",
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 783,
    beneficiary_name: "TISSA BIANI AZZAHRA",
    phone_number: "081288910345",
    email: "tissa_b@yahoo.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: "PROKLAMASI DEPOK",
    account_number: "6610822710",
    tax_percentage: 15,
    npwp: "45.804.192.8-412.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "DIAN ESTINING ADHI",
    beneficiary_type: "Personal",
    address: "Perum Pondok Kirana Asri Blok B1 Jl. Teluk Bayur",
    rt: "006",
    rw: "007",
    province: "Jawa Barat",
    city: "Depok",
    district: "Sukmajaya",
    sub_district: "Sukmajaya",
    postal_code: "16412",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 465,
    beneficiary_name: "PT VISI OPTIMA INDONESIA",
    phone_number: null,
    email: null,
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: "PASAR MINGGU",
    account_number: "1285001881",
    tax_percentage: 15,
    npwp: "90.485.212.6-065.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "PT. VISI OPTIMA INDONESIA",
    beneficiary_type: "Company",
    address: null,
    rt: null,
    rw: null,
    province: null,
    city: null,
    district: null,
    sub_district: null,
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 603,
    beneficiary_name: "ANDRI CAHYA UTAMA",
    phone_number: "085643321100",
    email: "tommykaloka@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: "SUDIRMAN",
    account_number: "0374071226",
    tax_percentage: 15,
    npwp: "78.378.108.1-541.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "ANDRI CAHYA UTAMA, SE",
    beneficiary_type: "Personal",
    address: "Bausasran Dn 3/596",
    rt: "041",
    rw: "011",
    province: "DI Yogyakarta",
    city: "Yogyakarta",
    district: "Danurejan",
    sub_district: "Bausasran",
    postal_code: "55211",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 467,
    beneficiary_name: "RIZKY FEBIAN ADRIANSYAH",
    phone_number: null,
    email: "rizkyfbian77@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: null,
    account_number: "4377779800",
    tax_percentage: 15,
    npwp: "85.462.067.1-435.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "RIZKY FEBIAN ANDRIANSYAH",
    beneficiary_type: "Personal",
    address: "Jl Bima Duta 3 No.5",
    rt: "001",
    rw: "011",
    province: "Jawa Barat",
    city: "Bekasi",
    district: "Tambun Selatan",
    sub_district: "Lambangsari",
    postal_code: "17510",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 827,
    beneficiary_name: "RAYMOND ADITYA CHRISTIANDO",
    phone_number: "08561968411",
    email: "adityachristiandoraymond@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: null,
    account_number: "0980116336",
    tax_percentage: 15,
    npwp: "76.014.529.2-507.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "RAYMOND ADITYA C",
    beneficiary_type: "Personal",
    address: "Dk Bangsri",
    rt: "003",
    rw: "004",
    province: "Jawa Tengah",
    city: "Pati",
    district: "Margorejo",
    sub_district: "Muktiharjo",
    postal_code: "59163",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 568,
    beneficiary_name: "PT TIGA RAMBU",
    phone_number: null,
    email: null,
    payment_currency: "IDR",
    bank_name: null,
    bank_address: null,
    account_number: null,
    tax_percentage: 30,
    npwp: null,
    auto_payout: null,
    notes: null,
    bank_account_holder: null,
    beneficiary_type: "Company",
    address: null,
    rt: null,
    rw: null,
    province: null,
    city: null,
    district: null,
    sub_district: null,
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 571,
    beneficiary_name: "HILMAN DARMAWAN CP",
    phone_number: "08129807070",
    email: "hilman.mr@gmail.com",
    payment_currency: "IDR",
    bank_name: "MANDIRI",
    bank_address: "JAKARTA PANGLIMA POLIM",
    account_number: "9000027413617",
    tax_percentage: 15,
    npwp: "93.650.055.2-014.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "HILMAN DARMAWAN C.P",
    beneficiary_type: "Personal",
    address: "Jl Kemang Utara I No.6",
    rt: "010",
    rw: "001",
    province: "DKI Jakarta",
    city: "Jakarta Selatan",
    district: "Mampang Prapatan",
    sub_district: "Bangka",
    postal_code: "12730",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 573,
    beneficiary_name: "DJAKA PURNAMA HK",
    phone_number: "0811210446",
    email: "cherika_h@protonmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: "DAGO",
    account_number: "0083287664",
    tax_percentage: 15,
    npwp: "06.122.499.4-423.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "DJAKA PURNAMA H.K",
    beneficiary_type: "Personal",
    address: "Jl Cigadung Selatan No.95 A",
    rt: "004",
    rw: "008",
    province: "Jawa Barat",
    city: "Bandung",
    district: "Cibeunying Kaler",
    sub_district: "Cigadung",
    postal_code: "40191",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 575,
    beneficiary_name: "ALIF GUSTAKHIYAT",
    phone_number: "082234339177",
    email: "dimar.music.management.2020@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: null,
    account_number: "1771503492",
    tax_percentage: 15,
    npwp: "89.368.214.6-647.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "JAJAK WICAKSONO",
    beneficiary_type: "Personal",
    address: "Kayu Tinggi",
    rt: "008",
    rw: "003",
    province: "DKI Jakarta",
    city: "Jakarta Timur",
    district: "Cakung",
    sub_district: "Cakung Timur",
    postal_code: null,
    c_address: "Jl Kh Fahrudin 04",
    c_rt: "003",
    c_rw: "003",
    c_province: "Jawa Timur",
    c_city: "Ponorogo",
    c_district: "Ponorogro",
    c_sub_district: "Kauman",
    c_postal_code: "63414",
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 576,
    beneficiary_name: "AHMAD AFRIYANA",
    phone_number: "082116515774",
    email: "ahmad.afriyana@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: "RAJAWALI",
    account_number: "2810056153",
    tax_percentage: 15,
    npwp: "94.728.651.4-428.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "AHMAD ARIYANA",
    beneficiary_type: "Personal",
    address: "Jl Arjuna Simpang",
    rt: "001",
    rw: "001",
    province: "Jawa Barat",
    city: "Bandung",
    district: "Andir",
    sub_district: "Ciroyom",
    postal_code: "40182",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 583,
    beneficiary_name: "AGUS SUSANTO",
    phone_number: null,
    email: null,
    payment_currency: "IDR",
    bank_name: null,
    bank_address: null,
    account_number: null,
    tax_percentage: 30,
    npwp: null,
    auto_payout: null,
    notes: null,
    bank_account_holder: null,
    beneficiary_type: "Personal",
    address: null,
    rt: null,
    rw: null,
    province: null,
    city: null,
    district: null,
    sub_district: null,
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 591,
    beneficiary_name: "YUSUF SYAHAILATUA",
    phone_number: "081293432991",
    email: "cevinsahilatua75@gmail.com",
    payment_currency: "IDR",
    bank_name: "BCA",
    bank_address: null,
    account_number: "1671398934",
    tax_percentage: 15,
    npwp: "66.543.249.8-023.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "YUSUF SYAHILATUA",
    beneficiary_type: "Personal",
    address: "Jl Kramat Sentiong I G 38",
    rt: "006",
    rw: "005",
    province: "DKI Jakarta",
    city: "Jakarta Pusat",
    district: "Senen",
    sub_district: "Kramat",
    postal_code: null,
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 592,
    beneficiary_name: "DIDIK PRASETYO",
    phone_number: "02129860798",
    email: "ip.didikempot@gmail.com",
    payment_currency: "IDR",
    bank_name: "MANDIRI",
    bank_address: "NGAWI",
    account_number: "1710006824703",
    tax_percentage: 15,
    npwp: "96.149.393.9-646.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "PUTRI",
    beneficiary_type: "Personal",
    address: "Pentuk Pelem",
    rt: "004",
    rw: "005",
    province: "Jawa Timur",
    city: "Ngawi",
    district: "Kendal",
    sub_district: "Majasem",
    postal_code: "53261",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 597,
    beneficiary_name: "MUHAMAD RIZKI NUR RACHMAN",
    phone_number: "0895356866616",
    email: "rizkinurrahman107@gmail.com",
    payment_currency: "IDR",
    bank_name: "SEABANK",
    bank_address: "JAKARTA",
    account_number: "901778354202",
    tax_percentage: 15,
    npwp: "95.437.140.7-008.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "M. RIZKI NUR RACHMAN",
    beneficiary_type: "Personal",
    address: "Jl Kapuk 3 No.40",
    rt: "003",
    rw: "005",
    province: "DKI Jakarta",
    city: "Jakarta Timur",
    district: "Duren Sawit",
    sub_district: "Klender",
    postal_code: "13470",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
  {
    code: 701,
    beneficiary_name: "DJAUHAR ZAHARSYAH FACHRUDIN ROESLI",
    phone_number: "081573008438",
    email: "roeslihami@gmail.com",
    payment_currency: "IDR",
    bank_name: "MANDIRI",
    bank_address: null,
    account_number: "1310004324291",
    tax_percentage: 15,
    npwp: "35.657.409.5-423.000",
    auto_payout: null,
    notes: null,
    bank_account_holder: "LAHAMI KHRISNA PARANA ROESLI",
    beneficiary_type: "Personal",
    address: "Jl Supratman No.59",
    rt: "006",
    rw: "004",
    province: "Jawa Barat",
    city: "Bandung",
    district: "Bandung Wetan",
    sub_district: "Cihapit",
    postal_code: "40114",
    c_address: null,
    c_rt: null,
    c_rw: null,
    c_province: null,
    c_city: null,
    c_district: null,
    c_sub_district: null,
    c_postal_code: null,
    created_at: "2025-01-17T05:50:17.623031Z",
    updated_at: "2025-01-17T05:50:17.623031Z",
  },
];

export const formatedDummyData = dummyTableData.map((item) => {
  return {
    code: item.code ?? null,
    beneficiaryName: item.beneficiary_name ?? null,
    createdDate: item.created_at ?? null,
    categories: [],
    status: null,
  };
});
